name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout repository
        uses: actions/checkout@v4

      - name: 🐦 Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'  # You can change this to 'stable' or any version

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🧹 Analyze project
        run: flutter analyze

      - name: 🧪 Run tests
        run: flutter test

      - name: 📱 Build APK (Android)
        run: flutter build apk --release

      - name: 📤 Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
